### ISSUE TITLE
player object  not found error

### ISSUE THREAD

**Issue by mavisakalyan** [UpstreetAI/monorepo#581]
![Image](https://github.com/user-attachments/assets/3a77a7e6-ed22-46f1-b2d5-dedb453c1e95)

To replicate just chat with any agent.

**Comment by AbdurrehmanSubhani** [comment]
Fix for both issues in relative PR's:
- https://github.com/UpstreetAI/monorepo/pull/583/
- https://github.com/UpstreetAI/monorepo/pull/584/

**Comment by AbdurrehmanSubhani** [comment]
PR for syncing playerSpec player addition:
https://github.com/UpstreetAI/monorepo/pull/602
